### ISSUE TITLE
Possible spelling mistake

### ISSUE THREAD

**Issue by kaubu** [jdonland/talmey1919#8]
On Page 20 of `talmey1919.pdf` it says:

> An apostrophe is to be used instead of the a so that no isolated 1 remains: la **una**—la altru or l’**unu**—l’altru

It seems to have changed *una* to *unu*, not helped in the least by the fact that both are valid words.

**Comment by jdonland** [comment]
Good catch!

**Comment by kaubu** [comment]
No problem, thanks for this excellent resource!
